import { LockKeyhole, Sparkles, Workflow } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Home() {
  return <div className="min-h-screen bg-[#f7f6f2] text-[#1e2927]">
    <header className="mx-auto flex max-w-6xl items-center px-6 py-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#1e2927] text-[#e7c98b]"><Sparkles size={18}/></div><span className="font-serif text-xl font-semibold tracking-tight">Entry Atelier</span></div></header>
    <main className="mx-auto grid max-w-6xl gap-16 px-6 pb-20 pt-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><section><p className="mb-5 text-sm font-semibold uppercase tracking-[.24em] text-[#a57b36]">Form management, refined</p><h1 className="max-w-2xl font-serif text-5xl leading-[1.08] tracking-tight md:text-7xl">大会 エントリー用 フォーム</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5e6762]">大会エントリーを円滑に進める用のサイトです。管理画面から管理できます。</p><div className="mt-9"><p className="text-sm text-[#6f7771]">公開フォームは管理者から共有された専用リンクでご利用ください。</p></div></section><section className="relative"><div className="absolute -inset-8 rounded-[3rem] bg-[#e7dfcf]/60 blur-3xl"/><div className="relative rounded-[2rem] border border-[#dedbd1] bg-white p-6 shadow-[0_24px_80px_rgba(30,41,39,.10)]"><div className="mb-8 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#a57b36]">Overview</p><p className="mt-2 font-serif text-2xl">受付の全体像</p></div><div className="rounded-full bg-[#eef3ed] px-3 py-1 text-xs text-[#59715f]">Live</div></div><div className="grid gap-3"><div className="rounded-2xl bg-[#f5f7f3] p-5"><div className="mb-4 flex items-center justify-between"><span className="text-sm text-[#6f7771]">今月の回答</span><Workflow size={18} className="text-[#a57b36]"/></div><p className="font-serif text-4xl">248</p><p className="mt-2 text-xs text-[#7e877f]">前月比 +18.4%</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-[#e6e4dc] p-4"><LockKeyhole size={17} className="mb-5 text-[#a57b36]"/><p className="text-sm font-medium">安全な通知</p><p className="mt-1 text-xs text-[#7e877f]">サーバー経由</p></div><div className="rounded-2xl border border-[#e6e4dc] p-4"><Sparkles size={17} className="mb-5 text-[#a57b36]"/><p className="text-sm font-medium">柔軟な質問</p><p className="mt-1 text-xs text-[#7e877f]">5つの形式</p></div></div></div></div></section></main>
  </div>;
}
