const API_ENDPOINT = ''; // 安全なサーバーAPIを使う場合はここに設定
const seed = {id:1,title:'エントリーフォーム',slug:'entry',description:'必要事項をご入力ください。',status:'open',successMessage:'回答を受け付けました。ありがとうございました。',questions:[{id:1,label:'お名前',description:'',type:'short_text',required:true,options:[]},{id:2,label:'メールアドレス',description:'ご連絡可能なアドレスをご入力ください。',type:'email',required:true,options:[]},{id:3,label:'お問い合わせ内容',description:'',type:'long_text',required:true,options:[]}]};
let state=JSON.parse(localStorage.getItem('entry-atelier-state')||'null')||{forms:[seed],selected:1,responses:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('entry-atelier-state',JSON.stringify(state));}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function current(){return state.forms.find(f=>f.id===state.selected)||state.forms[0]}
function renderPublic(){const f=current();const root=$('#form-root');if(!f||f.status!=='open'){root.innerHTML='<div class="empty">このフォームは現在受付していません。</div>';return}root.innerHTML=`<h2>${esc(f.title)}</h2><p class="intro">${esc(f.description)}</p><form id="public-form">${f.questions.map((q,i)=>`<div class="question"><label>${String(i+1).padStart(2,'0')}　${esc(q.label)}${q.required?'<span class="required">*</span>':''}</label>${q.description?`<small>${esc(q.description)}</small>`:''}${control(q)}</div>`).join('')}<button class="primary" type="submit">回答を送信する　→</button><p class="muted" style="font-size:12px;text-align:center;margin-top:15px">送信内容は安全に処理されます。</p></form>`;$('#public-form').onsubmit=submitPublic}
function control(q){const name=`q-${q.id}`;if(q.type==='long_text')return `<textarea name="${name}" ${q.required?'required':''}></textarea>`;if(q.type==='email')return `<input type="email" name="${name}" ${q.required?'required':''}>`;if(q.type==='single_choice')return q.options.map(o=>`<label class="choice"><input type="radio" name="${name}" value="${esc(o)}" ${q.required?'required':''}>${esc(o)}</label>`).join('');if(q.type==='multiple_choice')return q.options.map(o=>`<label class="choice"><input type="checkbox" name="${name}" value="${esc(o)}">${esc(o)}</label>`).join('');return `<input name="${name}" ${q.required?'required':''}>`}
async function submitPublic(e){e.preventDefault();const f=current(), data={};f.questions.forEach(q=>{const els=[...e.target.querySelectorAll(`[name="q-${q.id}"]`)];data[q.id]=q.type==='multiple_choice'?els.filter(x=>x.checked).map(x=>x.value):els.find(x=>x.checked)?.value||els[0]?.value||''});const submission={id:Date.now(),formId:f.id,submittedAt:new Date().toISOString(),status:'received',answers:data};try{if(API_ENDPOINT){const r=await fetch(API_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form:f,submission})});if(!r.ok)throw new Error('送信に失敗しました')}else{state.responses.unshift(submission);persist()}e.target.innerHTML=`<div class="empty" style="text-align:center;padding:40px 0"><strong style="font-family:'Playfair Display',serif;font-size:25px;display:block;margin-bottom:10px">ありがとうございます。</strong>${esc(f.successMessage)}</div>`}catch(err){toast('送信に失敗しました。設定を確認してください。')}}
function renderAdmin(){const f=current();$('#form-list').innerHTML=state.forms.map(x=>`<button class="list-item ${x.id===state.selected?'selected':''}" data-id="${x.id}">${esc(x.title)}<small>/${esc(x.slug)} · ${x.status==='open'?'受付中':x.status==='closed'?'終了':'下書き'}</small></button>`).join('');document.querySelectorAll('.list-item').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.id);persist();renderAll()});$('#title').value=f.title;$('#slug').value=f.slug;$('#description').value=f.description||'';$('#status').value=f.status;$('#successMessage').value=f.successMessage||'';$('#questions').innerHTML=f.questions.map((q,i)=>`<div class="question-card"><div class="row"><input data-q="${i}" data-key="label" value="${esc(q.label)}" placeholder="質問文"><select data-q="${i}" data-key="type">${[['short_text','短文'],['long_text','長文'],['email','メール'],['single_choice','単一選択'],['multiple_choice','複数選択']].map(([v,l])=>`<option value="${v}" ${q.type===v?'selected':''}>${l}</option>`).join('')}</select></div><input data-q="${i}" data-key="description" value="${esc(q.description||'')}" placeholder="補足説明（任意）">${['single_choice','multiple_choice'].includes(q.type)?`<input data-q="${i}" data-key="options" value="${esc(q.options.join(', '))}" placeholder="選択肢をカンマ区切りで入力">`:''}<div class="actions"><label><input type="checkbox" data-q="${i}" data-key="required" ${q.required?'checked':''}> 必須回答</label><span><button data-move="up" data-q="${i}" ${i===0?'disabled':''}>↑</button><button data-move="down" data-q="${i}" ${i===f.questions.length-1?'disabled':''}>↓</button><button class="danger" data-remove="${i}">削除</button></span></div></div>`).join('')||'<div class="empty">質問を追加してください。</div>';document.querySelectorAll('[data-q]').forEach(el=>el.onchange=()=>{const q=f.questions[Number(el.dataset.q)],k=el.dataset.key;q[k]=k==='required'?el.checked:k==='options'?el.value.split(',').map(x=>x.trim()).filter(Boolean):el.value;persist();renderPublic()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{f.questions.splice(Number(b.dataset.remove),1);persist();renderAll()});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.q),j=i+(b.dataset.move==='up'?-1:1);[f.questions[i],f.questions[j]]=[f.questions[j],f.questions[i]];persist();renderAll()});$('#responses').innerHTML=state.responses.filter(r=>r.formId===f.id).map(r=>`<div class="response"><span>回答 #${r.id}<br>${new Date(r.submittedAt).toLocaleString('ja-JP')}</span><span class="badge">受信済み</span></div>`).join('')||'<div class="empty">回答はまだありません。</div>'}
function renderAll(){renderPublic();renderAdmin()}
$('#save-form').onclick=()=>{const f=current();f.title=$('#title').value;f.slug=$('#slug').value;f.description=$('#description').value;f.status=$('#status').value;f.successMessage=$('#successMessage').value;persist();renderAll();toast('設定を保存しました')};$('#new-form').onclick=()=>{const id=Date.now();state.forms.push({id,title:'新しいフォーム',slug:'form-'+String(id).slice(-6),description:'',status:'draft',successMessage:'回答を受け付けました。ありがとうございました。',questions:[]});state.selected=id;persist();renderAll();toast('新しいフォームを作成しました')};$('#add-question').onclick=()=>{current().questions.push({id:Date.now(),label:'',description:'',type:'short_text',required:false,options:[]});persist();renderAll()};document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));if(b.dataset.view==='public')renderPublic();else renderAdmin()});renderAll();
